// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sklep_Internetowy_JW.DAL;

#nullable disable

namespace Sklep_Internetowy_JW.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20250310142344_data")]
    partial class data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sklep_Internetowy_JW.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Movies full of dynamic scenes, fights, and chases.",
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Movies designed to entertain and make the audience laugh.",
                            Name = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Movies that showcase intense emotions and serious situations.",
                            Name = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Movies full of tension, fear, and surprising plot twists.",
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Movies set in futuristic or technologically advanced worlds.",
                            Name = "Science Fiction"
                        });
                });

            modelBuilder.Entity("Sklep_Internetowy_JW.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 1,
                            Desc = "In a post-apocalyptic world, Max becomes part of a war for survival.",
                            Director = "George Miller",
                            Price = 19.99m,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 1,
                            Desc = "A former assassin fights for survival in a world full of killers.",
                            Director = "Chad Stahelski",
                            Price = 14.99m,
                            Title = "John Wick"
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 2,
                            Desc = "Four teenagers are sucked into a game where they must fight for their lives.",
                            Director = "Jake Kasdan",
                            Price = 12.99m,
                            Title = "Jumanji: Welcome to the Jungle"
                        },
                        new
                        {
                            FilmId = 4,
                            CategoryId = 2,
                            Desc = "Three men wake up after an unforgettable night in Las Vegas, not knowing what happened.",
                            Director = "Todd Phillips",
                            Price = 9.99m,
                            Title = "The Hangover"
                        },
                        new
                        {
                            FilmId = 5,
                            CategoryId = 3,
                            Desc = "A father struggles with adversity to provide a better life for his son.",
                            Director = "Gabriele Muccino",
                            Price = 11.99m,
                            Title = "The Pursuit of Happyness"
                        },
                        new
                        {
                            FilmId = 6,
                            CategoryId = 3,
                            Desc = "The story of a mathematician struggling with mental illness while his genius changes the world.",
                            Director = "Ron Howard",
                            Price = 13.99m,
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            FilmId = 7,
                            CategoryId = 4,
                            Desc = "A couple of paranormal investigators face a terrifying haunting case.",
                            Director = "James Wan",
                            Price = 15.99m,
                            Title = "The Conjuring"
                        },
                        new
                        {
                            FilmId = 8,
                            CategoryId = 4,
                            Desc = "A group of kids faces their fears against a demon that takes the form of a clown.",
                            Director = "Andrés Muschietti",
                            Price = 16.99m,
                            Title = "It"
                        },
                        new
                        {
                            FilmId = 9,
                            CategoryId = 5,
                            Desc = "Detective K uncovers a secret that could change the future of humanity.",
                            Director = "Denis Villeneuve",
                            Price = 18.99m,
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            FilmId = 10,
                            CategoryId = 5,
                            Desc = "A group of astronauts travel through black holes to save humanity.",
                            Director = "Christopher Nolan",
                            Price = 19.49m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            FilmId = 11,
                            CategoryId = 1,
                            Desc = "A policeman fights terrorists who have taken over a skyscraper.",
                            Director = "John McTiernan",
                            Price = 17.99m,
                            Title = "Die Hard"
                        },
                        new
                        {
                            FilmId = 12,
                            CategoryId = 2,
                            Desc = "The story of an eccentric hotel manager and his young assistant in a pre-World War II world.",
                            Director = "Wes Anderson",
                            Price = 13.49m,
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            FilmId = 13,
                            CategoryId = 3,
                            Desc = "A trapper fights for survival in the wilderness after a brutal animal attack.",
                            Director = "Alejandro González Iñárritu",
                            Price = 14.49m,
                            Title = "The Revenant"
                        },
                        new
                        {
                            FilmId = 14,
                            CategoryId = 4,
                            Desc = "A young African-American man uncovers a dark secret while visiting his girlfriend's family.",
                            Director = "Jordan Peele",
                            Price = 10.99m,
                            Title = "Get Out"
                        },
                        new
                        {
                            FilmId = 15,
                            CategoryId = 5,
                            Desc = "A computer programmer discovers that his reality is a virtual world created by machines.",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Price = 17.49m,
                            Title = "The Matrix"
                        },
                        new
                        {
                            FilmId = 16,
                            CategoryId = 1,
                            Desc = "Giant monsters attack Earth, and humanity fights back with giant robots.",
                            Director = "Guillermo del Toro",
                            Price = 18.99m,
                            Title = "Pacific Rim"
                        },
                        new
                        {
                            FilmId = 17,
                            CategoryId = 3,
                            Desc = "The story of Mark Zuckerberg and the creation of Facebook.",
                            Director = "David Fincher",
                            Price = 14.99m,
                            Title = "The Social Network"
                        },
                        new
                        {
                            FilmId = 18,
                            CategoryId = 5,
                            Desc = "A group of outlaws band together to stop a powerful villain from destroying the universe.",
                            Director = "James Gunn",
                            Price = 17.99m,
                            Title = "Guardians of the Galaxy"
                        },
                        new
                        {
                            FilmId = 19,
                            CategoryId = 3,
                            Desc = "A U.S. Marshal investigates the disappearance of a patient from a mental institution.",
                            Director = "Martin Scorsese",
                            Price = 12.99m,
                            Title = "Shutter Island"
                        },
                        new
                        {
                            FilmId = 20,
                            CategoryId = 4,
                            Desc = "A young FBI agent seeks the help of a cannibalistic serial killer to catch another murderer.",
                            Director = "Jonathan Demme",
                            Price = 16.49m,
                            Title = "The Silence of the Lambs"
                        });
                });

            modelBuilder.Entity("Sklep_Internetowy_JW.Models.Film", b =>
                {
                    b.HasOne("Sklep_Internetowy_JW.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sklep_Internetowy_JW.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
